"""Document export service — generates .docx and .pdf from analysis results, drafts, and reports.

Converts MyDenning outputs into properly formatted Word documents that lawyers
can use directly in their workflow: file in court, send to clients, attach to emails.
"""

import io
import re
from datetime import datetime, timezone

from docx import Document as DocxDocument
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

import structlog

logger = structlog.get_logger(__name__)


class ExportService:
    """Generates .docx files from structured legal content."""

    # Style constants
    FONT_NAME = "Calibri"
    HEADING_COLOR = RGBColor(0x1A, 0x1A, 0x2E)  # dark navy
    MUTED_COLOR = RGBColor(0x6B, 0x72, 0x80)  # gray-500

    def export_draft(self, draft_result: dict) -> bytes:
        """Export a generated draft (memo, contract, board resolution, etc.) to .docx."""
        doc = self._create_document()

        # Title
        draft_type = (draft_result.get("draft_type") or "Draft").replace("_", " ").title()
        self._add_title(doc, draft_type)

        # Metadata bar
        meta = doc.add_paragraph()
        meta.paragraph_format.space_after = Pt(12)
        run = meta.add_run(f"Generated by MyDenning  |  {datetime.now(timezone.utc).strftime('%B %d, %Y')}")
        run.font.size = Pt(9)
        run.font.color.rgb = self.MUTED_COLOR

        if draft_result.get("confidence_score") is not None:
            run = meta.add_run(f"  |  Confidence: {round(draft_result['confidence_score'] * 100)}%")
            run.font.size = Pt(9)
            run.font.color.rgb = self.MUTED_COLOR

        doc.add_paragraph()  # spacer

        # Main content
        content = draft_result.get("content", "")
        self._add_markdown_content(doc, content)

        # Citations section
        citations = draft_result.get("citations", [])
        if citations:
            doc.add_page_break()
            self._add_heading(doc, "Sources Cited", level=1)
            for i, cite in enumerate(citations, 1):
                text = cite.get("citation_text") or cite.get("text", "")
                source = cite.get("source_title") or cite.get("source", "")
                p = doc.add_paragraph(style="List Number")
                run = p.add_run(text)
                run.font.bold = True
                if source:
                    p.add_run(f"\n{source}").font.color.rgb = self.MUTED_COLOR

        # Risk flags
        risk_flags = draft_result.get("risk_flags", [])
        if risk_flags:
            self._add_heading(doc, "Risk Flags", level=1)
            for flag in risk_flags:
                p = doc.add_paragraph(style="List Bullet")
                run = p.add_run(flag)
                run.font.color.rgb = RGBColor(0xDC, 0x26, 0x26)

        # Assumptions
        assumptions = draft_result.get("assumptions", [])
        if assumptions:
            self._add_heading(doc, "Assumptions", level=1)
            for assumption in assumptions:
                doc.add_paragraph(assumption, style="List Bullet")

        # Disclaimer
        self._add_disclaimer(doc)

        return self._to_bytes(doc)

    def export_review(self, review_result: dict, document_title: str = "") -> bytes:
        """Export a document review (clause extraction + risk analysis) to .docx."""
        doc = self._create_document()
        self._add_title(doc, "Document Review Report")

        if document_title:
            p = doc.add_paragraph()
            p.add_run("Document: ").font.bold = True
            p.add_run(document_title)

        # Summary
        summary = review_result.get("summary", "")
        if summary:
            self._add_heading(doc, "Summary", level=1)
            doc.add_paragraph(summary)

        # Overall risk
        risk = review_result.get("overall_risk_level", "")
        if risk:
            p = doc.add_paragraph()
            p.add_run("Overall Risk Level: ").font.bold = True
            run = p.add_run(risk.upper())
            run.font.bold = True
            if risk in ("critical", "high"):
                run.font.color.rgb = RGBColor(0xDC, 0x26, 0x26)
            elif risk == "medium":
                run.font.color.rgb = RGBColor(0xD9, 0x77, 0x06)

        # Clauses table
        clauses = review_result.get("clauses", [])
        if clauses:
            self._add_heading(doc, "Extracted Clauses", level=1)
            table = doc.add_table(rows=1, cols=4)
            table.style = "Table Grid"
            table.alignment = WD_TABLE_ALIGNMENT.CENTER
            headers = table.rows[0].cells
            for i, text in enumerate(["Clause Type", "Text (excerpt)", "Risk", "Notes"]):
                headers[i].text = text
                for paragraph in headers[i].paragraphs:
                    for run in paragraph.runs:
                        run.font.bold = True
                        run.font.size = Pt(9)

            for clause in clauses:
                row = table.add_row().cells
                row[0].text = (clause.get("clause_type") or "").replace("_", " ").title()
                clause_text = clause.get("clause_text", "")
                row[1].text = clause_text[:200] + ("..." if len(clause_text) > 200 else "")
                row[2].text = (clause.get("risk_level") or "—").upper()
                row[3].text = clause.get("risk_notes") or "—"
                for cell in row:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.size = Pt(8)

        # Missing clauses
        missing = review_result.get("missing_clauses", [])
        if missing:
            self._add_heading(doc, "Missing Clauses", level=1)
            for m in missing:
                doc.add_paragraph(m, style="List Bullet")

        self._add_disclaimer(doc)
        return self._to_bytes(doc)

    def export_redline(self, redline_result: dict) -> bytes:
        """Export a redline comparison to .docx with tracked-changes styling."""
        doc = self._create_document()
        self._add_title(doc, "Redline Comparison")

        doc1 = redline_result.get("doc1", {})
        doc2 = redline_result.get("doc2", {})
        p = doc.add_paragraph()
        p.add_run("Original: ").font.bold = True
        p.add_run(doc1.get("title", "Document 1"))
        p = doc.add_paragraph()
        p.add_run("Revised: ").font.bold = True
        p.add_run(doc2.get("title", "Document 2"))

        # Summary stats
        p = doc.add_paragraph()
        p.add_run(f"\nTotal changes: {redline_result.get('total_changes', 0)}  |  ")
        p.add_run(f"Additions: {redline_result.get('additions', 0)}  |  ")
        p.add_run(f"Deletions: {redline_result.get('deletions', 0)}  |  ")
        p.add_run(f"Modifications: {redline_result.get('modifications', 0)}")

        if redline_result.get("summary"):
            self._add_heading(doc, "Summary", level=1)
            doc.add_paragraph(redline_result["summary"])

        # Changes
        changes = redline_result.get("changes", [])
        if changes:
            self._add_heading(doc, "Changes", level=1)
            for i, change in enumerate(changes, 1):
                self._add_heading(doc, f"Change {i}: {(change.get('change_type') or '').title()}", level=2)

                if change.get("location"):
                    p = doc.add_paragraph()
                    p.add_run("Location: ").font.bold = True
                    p.add_run(change["location"])

                if change.get("original_text"):
                    p = doc.add_paragraph()
                    p.add_run("Original: ").font.bold = True
                    run = p.add_run(change["original_text"])
                    run.font.color.rgb = RGBColor(0xDC, 0x26, 0x26)
                    run.font.strike = True

                if change.get("new_text"):
                    p = doc.add_paragraph()
                    p.add_run("New: ").font.bold = True
                    run = p.add_run(change["new_text"])
                    run.font.color.rgb = RGBColor(0x16, 0xA3, 0x4A)
                    run.font.underline = True

                if change.get("legal_significance"):
                    p = doc.add_paragraph()
                    p.add_run("Legal significance: ").font.bold = True
                    p.add_run(change["legal_significance"])

                if change.get("risk_level"):
                    p = doc.add_paragraph()
                    p.add_run("Risk: ").font.bold = True
                    p.add_run(change["risk_level"].upper())

                if change.get("commentary"):
                    p = doc.add_paragraph()
                    p.add_run("Commentary: ").font.italic = True
                    p.add_run(change["commentary"]).font.italic = True

        self._add_disclaimer(doc)
        return self._to_bytes(doc)

    def export_privilege_log(self, entries: list[dict], matter_title: str = "") -> bytes:
        """Export a privilege log as a formatted table in .docx."""
        doc = self._create_document()
        self._add_title(doc, "Privilege Log")

        if matter_title:
            p = doc.add_paragraph()
            p.add_run("Matter: ").font.bold = True
            p.add_run(matter_title)

        p = doc.add_paragraph()
        p.add_run(f"Date: {datetime.now(timezone.utc).strftime('%B %d, %Y')}  |  Entries: {len(entries)}")
        p.paragraph_format.space_after = Pt(12)

        if entries:
            table = doc.add_table(rows=1, cols=6)
            table.style = "Table Grid"
            headers = ["#", "Document", "Date", "Privilege", "Basis", "Scope"]
            for i, text in enumerate(headers):
                headers_row = table.rows[0].cells
                headers_row[i].text = text
                for paragraph in headers_row[i].paragraphs:
                    for run in paragraph.runs:
                        run.font.bold = True
                        run.font.size = Pt(9)

            for idx, entry in enumerate(entries, 1):
                row = table.add_row().cells
                row[0].text = str(idx)
                row[1].text = entry.get("document_title", "—")
                row[2].text = entry.get("date_asserted", "—")[:10] if entry.get("date_asserted") else "—"
                row[3].text = (entry.get("privilege_type") or "—").replace("_", " ").title()
                row[4].text = entry.get("basis", "—")
                row[5].text = entry.get("scope", "—") or "—"
                for cell in row:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.size = Pt(8)

        self._add_disclaimer(doc)
        return self._to_bytes(doc)

    def export_risk_matrix(self, risk_result: dict, document_title: str = "") -> bytes:
        """Export a risk assessment matrix to .docx."""
        doc = self._create_document()
        self._add_title(doc, "Risk Assessment Matrix")

        if document_title:
            p = doc.add_paragraph()
            p.add_run("Document: ").font.bold = True
            p.add_run(document_title)

        if risk_result.get("summary"):
            self._add_heading(doc, "Summary", level=1)
            doc.add_paragraph(risk_result["summary"])

        risks = risk_result.get("risks", [])
        if risks:
            self._add_heading(doc, "Risk Matrix", level=1)
            table = doc.add_table(rows=1, cols=5)
            table.style = "Table Grid"
            for i, text in enumerate(["Risk Area", "Likelihood", "Impact", "Level", "Mitigation"]):
                table.rows[0].cells[i].text = text
                for paragraph in table.rows[0].cells[i].paragraphs:
                    for run in paragraph.runs:
                        run.font.bold = True
                        run.font.size = Pt(9)

            for risk in risks:
                row = table.add_row().cells
                row[0].text = str(risk.get("risk_area", "—"))
                row[1].text = str(risk.get("likelihood", "—"))
                row[2].text = str(risk.get("impact", "—"))
                row[3].text = str(risk.get("risk_level", "—")).upper()
                row[4].text = str(risk.get("mitigation", "—"))
                for cell in row:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.size = Pt(8)

        self._add_disclaimer(doc)
        return self._to_bytes(doc)

    def export_invoice(self, invoice: dict, org_name: str = "", client_name: str = "") -> bytes:
        """Export an invoice as a formatted .docx document."""
        doc = self._create_document()
        self._add_title(doc, "INVOICE")

        # Header info
        if org_name:
            p = doc.add_paragraph()
            run = p.add_run(org_name)
            run.font.size = Pt(14)
            run.font.bold = True

        p = doc.add_paragraph()
        p.add_run(f"Invoice #: ").font.bold = True
        p.add_run(invoice.get("invoice_number", ""))
        p = doc.add_paragraph()
        p.add_run(f"Date: ").font.bold = True
        p.add_run(invoice.get("issue_date", "")[:10])
        p = doc.add_paragraph()
        p.add_run(f"Due Date: ").font.bold = True
        p.add_run(invoice.get("due_date", "")[:10])

        if client_name:
            doc.add_paragraph()
            p = doc.add_paragraph()
            p.add_run("Bill To: ").font.bold = True
            p.add_run(client_name)

        doc.add_paragraph()

        # Line items table
        line_items = invoice.get("line_items", [])
        if line_items:
            table = doc.add_table(rows=1, cols=5)
            table.style = "Table Grid"
            for i, text in enumerate(["Date", "Description", "Hours", "Rate", "Amount"]):
                table.rows[0].cells[i].text = text
                for paragraph in table.rows[0].cells[i].paragraphs:
                    for run in paragraph.runs:
                        run.font.bold = True
                        run.font.size = Pt(9)

            for item in line_items:
                row = table.add_row().cells
                row[0].text = str(item.get("date", ""))[:10]
                row[1].text = str(item.get("description", ""))
                row[2].text = str(item.get("hours", ""))
                row[3].text = str(item.get("rate", ""))
                row[4].text = f"{item.get('amount', 0):,.2f}"
                for cell in row:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.size = Pt(9)

        # Totals
        doc.add_paragraph()
        currency = invoice.get("currency", "NGN")

        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        p.add_run(f"Subtotal: {currency} {invoice.get('subtotal', 0):,.2f}")

        if invoice.get("tax_amount", 0) > 0:
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
            p.add_run(f"Tax ({invoice.get('tax_rate', 0)}%): {currency} {invoice.get('tax_amount', 0):,.2f}")

        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        run = p.add_run(f"Total: {currency} {invoice.get('total', 0):,.2f}")
        run.font.bold = True
        run.font.size = Pt(14)

        if invoice.get("amount_paid", 0) > 0:
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
            p.add_run(f"Paid: {currency} {invoice.get('amount_paid', 0):,.2f}")
            balance = invoice.get("total", 0) - invoice.get("amount_paid", 0)
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
            run = p.add_run(f"Balance Due: {currency} {balance:,.2f}")
            run.font.bold = True

        if invoice.get("notes"):
            doc.add_paragraph()
            p = doc.add_paragraph()
            p.add_run("Notes: ").font.bold = True
            p.add_run(invoice["notes"])

        if invoice.get("payment_terms"):
            p = doc.add_paragraph()
            p.add_run("Payment Terms: ").font.bold = True
            p.add_run(invoice["payment_terms"])

        self._add_disclaimer(doc)
        return self._to_bytes(doc)

    # ===== Internal helpers =====

    def _create_document(self) -> DocxDocument:
        doc = DocxDocument()
        # Set default font
        style = doc.styles["Normal"]
        font = style.font
        font.name = self.FONT_NAME
        font.size = Pt(11)
        style.paragraph_format.space_after = Pt(6)
        style.paragraph_format.line_spacing = 1.15
        return doc

    def _add_title(self, doc: DocxDocument, text: str) -> None:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = p.add_run(text)
        run.font.size = Pt(22)
        run.font.bold = True
        run.font.color.rgb = self.HEADING_COLOR
        p.paragraph_format.space_after = Pt(4)

    def _add_heading(self, doc: DocxDocument, text: str, level: int = 1) -> None:
        heading = doc.add_heading(text, level=level)
        for run in heading.runs:
            run.font.color.rgb = self.HEADING_COLOR

    def _add_markdown_content(self, doc: DocxDocument, markdown_text: str) -> None:
        """Convert basic markdown to Word paragraphs."""
        lines = markdown_text.split("\n")
        for line in lines:
            stripped = line.strip()
            if not stripped:
                doc.add_paragraph()
                continue

            # Headings
            heading_match = re.match(r'^(#{1,4})\s+(.+)$', stripped)
            if heading_match:
                level = len(heading_match.group(1))
                self._add_heading(doc, heading_match.group(2), level=level)
                continue

            # Bullet points
            if stripped.startswith("- ") or stripped.startswith("* "):
                doc.add_paragraph(stripped[2:], style="List Bullet")
                continue

            # Numbered lists
            num_match = re.match(r'^\d+\.\s+(.+)$', stripped)
            if num_match:
                doc.add_paragraph(num_match.group(1), style="List Number")
                continue

            # Regular paragraph with bold/italic
            p = doc.add_paragraph()
            self._add_formatted_runs(p, stripped)

    def _add_formatted_runs(self, paragraph, text: str) -> None:
        """Parse basic markdown inline formatting (**bold**, *italic*)."""
        parts = re.split(r'(\*\*.*?\*\*|\*.*?\*)', text)
        for part in parts:
            if part.startswith("**") and part.endswith("**"):
                run = paragraph.add_run(part[2:-2])
                run.font.bold = True
            elif part.startswith("*") and part.endswith("*"):
                run = paragraph.add_run(part[1:-1])
                run.font.italic = True
            else:
                paragraph.add_run(part)

    def _add_disclaimer(self, doc: DocxDocument) -> None:
        doc.add_paragraph()
        doc.add_paragraph()
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(
            "This document was generated by MyDenning Legal Intelligence. "
            "All outputs should be reviewed by licensed attorneys before use. "
            "This does not constitute legal advice."
        )
        run.font.size = Pt(8)
        run.font.italic = True
        run.font.color.rgb = self.MUTED_COLOR

    def _to_bytes(self, doc: DocxDocument) -> bytes:
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.read()
