"""CCPA / CPRA compliance playbook — California Consumer Privacy Act as amended."""

CCPA_PLAYBOOK = {
    "name": "CCPA/CPRA Compliance",
    "description": "Standard positions for reviewing service provider agreements and data processing terms under the California Consumer Privacy Act (CCPA) as amended by the California Privacy Rights Act (CPRA). Covers service provider obligations, consumer rights, opt-out requirements, and data sharing restrictions.",
    "document_type": "service_provider_agreement",
    "jurisdiction": "US",
    "clauses": [
        {
            "clause_type": "service_provider_certification",
            "clause_name": "Service Provider Certification",
            "position": "preferred",
            "standard_language": "The Service Provider certifies that it understands and will comply with the restrictions set forth in the CCPA (Cal. Civ. Code 1798.100 et seq.) and its implementing regulations. The Service Provider shall not: (a) sell or share the Personal Information; (b) retain, use, or disclose the Personal Information for any purpose other than the business purposes specified in this Agreement; (c) retain, use, or disclose the Personal Information outside of the direct business relationship between the Service Provider and the Business; or (d) combine the Personal Information with Personal Information received from other sources except as permitted by the CCPA.",
            "negotiation_notes": "This certification is required under CCPA Section 1798.140(ag) to qualify the vendor as a 'service provider' rather than a 'third party'. Without it, data sharing may be treated as a 'sale'.",
            "risk_if_deviated": "Without service provider certification, the data transfer may constitute a 'sale' under CCPA, triggering opt-out obligations and potential enforcement by the California Attorney General.",
            "importance_weight": 1.0,
            "order_index": 1,
        },
        {
            "clause_type": "consumer_rights_assistance",
            "clause_name": "Consumer Rights Request Assistance",
            "position": "preferred",
            "standard_language": "The Service Provider shall assist the Business in responding to verifiable consumer requests to know, delete, correct, or opt-out. The Service Provider shall: (a) notify the Business within 5 business days of receiving a consumer request directly; (b) provide all information necessary to fulfil the request; and (c) delete Personal Information upon the Business's instruction in connection with a consumer deletion request.",
            "risk_if_deviated": "CCPA requires businesses to respond to consumer requests within 45 days. Without Service Provider assistance, compliance may be impossible.",
            "importance_weight": 1.0,
            "order_index": 2,
        },
        {
            "clause_type": "do_not_sell",
            "clause_name": "Do Not Sell or Share Obligations",
            "position": "preferred",
            "standard_language": "The Service Provider shall not sell or share (as defined under the CCPA) any Personal Information received from the Business. The Service Provider shall not use Personal Information for cross-context behavioural advertising. The Service Provider shall honour all opt-out preference signals forwarded by the Business.",
            "unacceptable_patterns": ["right to use data for own purposes", "may share with affiliates", "data may be used for advertising"],
            "risk_if_deviated": "Using personal information for cross-context advertising or selling it triggers full CCPA compliance obligations including opt-out mechanisms and may expose both parties to enforcement.",
            "importance_weight": 1.0,
            "order_index": 3,
        },
        {
            "clause_type": "data_retention",
            "clause_name": "Data Minimisation and Retention",
            "position": "preferred",
            "standard_language": "The Service Provider shall not retain Personal Information for longer than reasonably necessary for the business purpose for which it was collected. The Service Provider shall establish and maintain a retention schedule and shall notify the Business before retaining data beyond the agreed retention period.",
            "risk_if_deviated": "CPRA added data minimisation requirements (Section 1798.100(c)). Over-retention may violate these requirements.",
            "importance_weight": 0.8,
            "order_index": 4,
        },
        {
            "clause_type": "security_obligations",
            "clause_name": "Reasonable Security Measures",
            "position": "preferred",
            "standard_language": "The Service Provider shall implement and maintain reasonable security procedures and practices appropriate to the nature of the Personal Information to protect it from unauthorised or illegal access, destruction, use, modification, or disclosure, consistent with the requirements of Cal. Civ. Code Section 1798.81.5.",
            "negotiation_notes": "CCPA provides a private right of action for data breaches resulting from failure to implement reasonable security (Section 1798.150). Ensure the Service Provider's security is adequate.",
            "risk_if_deviated": "Inadequate security exposes the Business to statutory damages of $100-$750 per consumer per incident under the CCPA private right of action.",
            "importance_weight": 1.0,
            "order_index": 5,
        },
        {
            "clause_type": "audit_rights",
            "clause_name": "Compliance Monitoring and Audit",
            "position": "preferred",
            "standard_language": "The Business shall have the right to take reasonable and appropriate steps to ensure that the Service Provider uses Personal Information in a manner consistent with the Business's obligations under the CCPA. The Service Provider shall make available to the Business all information necessary to demonstrate compliance, and the Business may conduct or commission an annual compliance assessment.",
            "risk_if_deviated": "CPRA regulations require businesses to exercise diligence over service providers. Without audit rights, the Business cannot demonstrate compliance.",
            "importance_weight": 0.9,
            "order_index": 6,
        },
        {
            "clause_type": "sub_contractor",
            "clause_name": "Sub-contractor Flow-Down",
            "position": "preferred",
            "standard_language": "The Service Provider shall notify the Business of any sub-contractors that will have access to Personal Information. The Service Provider shall enter into a written contract with each sub-contractor imposing the same obligations as those imposed on the Service Provider under this Agreement. The Service Provider shall remain fully liable for the acts and omissions of its sub-contractors.",
            "risk_if_deviated": "Without flow-down provisions, the Business loses visibility and control over downstream processing.",
            "importance_weight": 0.8,
            "order_index": 7,
        },
        {
            "clause_type": "sensitive_personal_information",
            "clause_name": "Sensitive Personal Information",
            "position": "preferred",
            "standard_language": "To the extent the Service Provider processes Sensitive Personal Information (as defined in CCPA Section 1798.140(ae)), the Service Provider shall limit its use to that which is strictly necessary and proportionate to achieve the purposes for which the Sensitive Personal Information was collected or processed, and shall not use Sensitive Personal Information for any purpose other than those specified in the Agreement.",
            "negotiation_notes": "CPRA introduced the concept of Sensitive Personal Information (SPI) with additional restrictions. Ensure the agreement addresses SPI specifically.",
            "risk_if_deviated": "Consumers have the right to limit the use of their SPI under Section 1798.121. Failure to honour this creates enforcement risk.",
            "importance_weight": 0.9,
            "order_index": 8,
        },
    ],
}
