"""Employment Agreement playbook — standard positions for employment contracts."""

EMPLOYMENT_AGREEMENT_PLAYBOOK = {
    "name": "Employment Agreement Playbook",
    "description": "Standard positions for reviewing employment agreements covering restrictive covenants, IP assignment, termination, confidentiality, and benefits.",
    "document_type": "employment_agreement",
    "jurisdiction": None,
    "clauses": [
        {
            "clause_type": "non_compete",
            "clause_name": "Non-Compete Restriction",
            "position": "preferred",
            "standard_language": "For a period of 12 months following termination of employment, the Employee shall not, directly or indirectly, engage in or provide services to any business that competes with the Company within the geographic areas in which the Company operates, provided that this restriction applies only to the specific business area in which the Employee was engaged during the last 12 months of employment.",
            "fallback_language": "Non-compete of 6 months with narrow geographic and activity scope. Garden leave as alternative.",
            "unacceptable_patterns": ["non-compete exceeding 24 months", "worldwide restriction", "restriction covering all company business lines", "no geographic limitation"],
            "negotiation_notes": "Enforceability varies significantly by jurisdiction. Nigerian courts apply the Nordenfelt reasonableness test. UK courts require the restriction to protect a legitimate business interest. Some US states (California) prohibit non-competes entirely. Always scope narrowly: duration, geography, and activity.",
            "risk_if_deviated": "Overly broad non-competes are likely unenforceable and may be struck down entirely rather than read down.",
            "approval_required_if": "Duration exceeds 12 months or scope is not geographically limited",
            "importance_weight": 1.0,
            "order_index": 1,
        },
        {
            "clause_type": "non_solicitation",
            "clause_name": "Non-Solicitation of Employees and Clients",
            "position": "preferred",
            "standard_language": "For a period of 12 months following termination, the Employee shall not: (a) solicit or entice away any employee of the Company with whom the Employee worked during the last 12 months of employment; or (b) solicit or divert the business of any client or customer of the Company with whom the Employee had material dealings during the last 12 months of employment.",
            "negotiation_notes": "Non-solicitation is generally more enforceable than non-compete. Ensure it is limited to employees/clients the employee actually worked with.",
            "importance_weight": 0.9,
            "order_index": 2,
        },
        {
            "clause_type": "intellectual_property",
            "clause_name": "IP Assignment and Work Product",
            "position": "preferred",
            "standard_language": "All intellectual property created by the Employee in the course of employment or using the Company's resources shall be the sole and exclusive property of the Company. The Employee hereby assigns to the Company all right, title, and interest in such intellectual property. The Employee shall execute all documents and take all actions reasonably necessary to perfect the Company's ownership.",
            "fallback_language": "IP created in the course of employment is owned by the Company. IP created outside working hours and without Company resources belongs to the Employee, subject to a non-exclusive licence to the Company where it relates to the Company's business.",
            "unacceptable_patterns": ["all IP belongs to employee", "no assignment clause", "assignment limited to patents only"],
            "negotiation_notes": "Standard in most jurisdictions. In the UK, IP created in the course of employment belongs to the employer by statute (CDPA 1988 s.11). In Nigeria, ensure explicit assignment as the default position may be less clear.",
            "importance_weight": 1.0,
            "order_index": 3,
        },
        {
            "clause_type": "termination",
            "clause_name": "Termination and Notice Period",
            "position": "preferred",
            "standard_language": "Either party may terminate the employment by giving not less than 3 months' prior written notice. The Company may terminate the employment immediately without notice for cause, including: (a) gross misconduct; (b) material breach of the employment agreement; (c) conviction of a criminal offence; or (d) persistent failure to perform duties after written warning. Upon termination, the Employee shall return all Company property and Confidential Information.",
            "negotiation_notes": "Notice periods vary by seniority: 1 month for junior, 3 months for mid-level, 6 months for senior/C-suite. Ensure the for-cause termination grounds are clearly defined.",
            "importance_weight": 0.8,
            "order_index": 4,
        },
        {
            "clause_type": "confidentiality",
            "clause_name": "Confidentiality Obligations",
            "position": "preferred",
            "standard_language": "During and after employment, the Employee shall not disclose, use, or make available to any person any Confidential Information of the Company except in the proper performance of their duties. This obligation survives termination of employment indefinitely with respect to trade secrets and for a period of 3 years with respect to other Confidential Information.",
            "importance_weight": 0.9,
            "order_index": 5,
        },
    ],
}
