"""GDPR Data Processing Agreement playbook — 15 required clauses per Articles 28, 32, 33, 44-49."""

GDPR_DPA_PLAYBOOK = {
    "name": "GDPR Data Processing Agreement",
    "description": "Standard positions for reviewing Data Processing Agreements under the EU General Data Protection Regulation. Covers all mandatory DPA clauses per GDPR Articles 28, 32, 33, and 44-49.",
    "document_type": "dpa",
    "jurisdiction": "EU",
    "clauses": [
        {
            "clause_type": "processing_purpose",
            "clause_name": "Subject Matter and Purpose of Processing",
            "position": "preferred",
            "standard_language": "The Processor shall process Personal Data only for the specific purposes set out in Annex 1 to this Agreement and strictly in accordance with the documented instructions of the Controller, unless required to do so by Union or Member State law to which the Processor is subject.",
            "negotiation_notes": "Ensure the purpose is narrowly defined. Reject broad or open-ended processing purposes. The annex should specify data categories, data subjects, processing operations, and retention periods.",
            "risk_if_deviated": "Broad processing purposes may result in unlawful processing under Article 5(1)(b) GDPR (purpose limitation). Regulatory fines up to 4% of annual global turnover.",
            "importance_weight": 1.0,
            "order_index": 1,
        },
        {
            "clause_type": "controller_instructions",
            "clause_name": "Processing on Controller Instructions Only",
            "position": "preferred",
            "standard_language": "The Processor shall process Personal Data only on documented instructions from the Controller, including with regard to transfers of Personal Data to a third country or an international organisation, unless required to do so by Union or Member State law; in such a case, the Processor shall inform the Controller of that legal requirement before processing, unless that law prohibits such information on important grounds of public interest.",
            "risk_if_deviated": "Processing outside Controller instructions constitutes a breach of Article 28(3)(a) GDPR and may make the Processor a Controller in its own right.",
            "importance_weight": 1.0,
            "order_index": 2,
        },
        {
            "clause_type": "confidentiality",
            "clause_name": "Confidentiality of Processing",
            "position": "preferred",
            "standard_language": "The Processor shall ensure that persons authorised to process the Personal Data have committed themselves to confidentiality or are under an appropriate statutory obligation of confidentiality.",
            "risk_if_deviated": "Required by Article 28(3)(b) GDPR. Absence may indicate inadequate organisational measures.",
            "importance_weight": 0.9,
            "order_index": 3,
        },
        {
            "clause_type": "security_measures",
            "clause_name": "Technical and Organisational Security Measures",
            "position": "preferred",
            "standard_language": "The Processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including as appropriate: (a) the pseudonymisation and encryption of Personal Data; (b) the ability to ensure the ongoing confidentiality, integrity, availability and resilience of processing systems and services; (c) the ability to restore the availability and access to Personal Data in a timely manner in the event of a physical or technical incident; (d) a process for regularly testing, assessing and evaluating the effectiveness of technical and organisational measures for ensuring the security of the processing.",
            "negotiation_notes": "Request the Processor to complete a security questionnaire or provide SOC 2 / ISO 27001 certification. Require specific measures to be listed in an annex.",
            "risk_if_deviated": "Article 32 GDPR requires appropriate security. Vague security commitments provide insufficient protection and may not satisfy the accountability principle.",
            "importance_weight": 1.0,
            "order_index": 4,
        },
        {
            "clause_type": "sub_processor",
            "clause_name": "Sub-processor Engagement",
            "position": "preferred",
            "standard_language": "The Processor shall not engage another processor (sub-processor) without prior specific or general written authorisation of the Controller. In the case of general written authorisation, the Processor shall inform the Controller of any intended changes concerning the addition or replacement of other processors, thereby giving the Controller the opportunity to object to such changes. The Processor shall impose the same data protection obligations as set out in this Agreement on any sub-processor by way of a contract.",
            "fallback_language": "The Processor may engage sub-processors subject to: (i) providing the Controller with at least 30 days' prior written notice of any new sub-processor; (ii) the Controller having the right to object on reasonable grounds; and (iii) the Processor remaining fully liable for the acts and omissions of its sub-processors.",
            "unacceptable_patterns": ["no notification required", "blanket consent to all sub-processors", "Controller waives right to object"],
            "negotiation_notes": "General authorisation with right to object is the market standard. Push for specific authorisation if dealing with sensitive data. Always require a current sub-processor list.",
            "risk_if_deviated": "Article 28(2) and (4) GDPR. Without sub-processor controls, the Controller loses visibility over the processing chain.",
            "importance_weight": 1.0,
            "order_index": 5,
        },
        {
            "clause_type": "data_subject_rights",
            "clause_name": "Assistance with Data Subject Rights",
            "position": "preferred",
            "standard_language": "Taking into account the nature of the processing, the Processor shall assist the Controller by appropriate technical and organisational measures, insofar as this is possible, for the fulfilment of the Controller's obligation to respond to requests for exercising the data subject's rights laid down in Chapter III of the GDPR.",
            "negotiation_notes": "Require the Processor to notify the Controller within 48 hours of receiving a data subject request and to provide reasonable assistance at no additional cost.",
            "risk_if_deviated": "Article 28(3)(e) GDPR. Without this, the Controller may be unable to meet the one-month response deadline under Article 12(3).",
            "importance_weight": 0.9,
            "order_index": 6,
        },
        {
            "clause_type": "breach_notification",
            "clause_name": "Personal Data Breach Notification",
            "position": "preferred",
            "standard_language": "The Processor shall notify the Controller without undue delay and in any event within 24 hours after becoming aware of a Personal Data breach. The notification shall include: (a) a description of the nature of the breach including the categories and approximate number of data subjects and records concerned; (b) the name and contact details of the data protection officer or other contact point; (c) a description of the likely consequences of the breach; (d) a description of the measures taken or proposed to be taken to address the breach.",
            "fallback_language": "The Processor shall notify the Controller without undue delay and in any event within 72 hours after becoming aware of a Personal Data breach, providing all information required under Article 33(3) GDPR.",
            "unacceptable_patterns": ["notification within 5 business days", "only material breaches", "best efforts to notify"],
            "negotiation_notes": "24 hours is preferred to give the Controller time to assess and notify the supervisory authority within the 72-hour deadline under Article 33. Never accept notification timelines longer than 72 hours.",
            "risk_if_deviated": "Articles 33 and 34 GDPR. Late notification can result in separate fines against the Controller for failing to notify the supervisory authority within 72 hours.",
            "importance_weight": 1.0,
            "order_index": 7,
        },
        {
            "clause_type": "data_deletion",
            "clause_name": "Deletion or Return of Data on Termination",
            "position": "preferred",
            "standard_language": "At the choice of the Controller, the Processor shall delete or return all Personal Data to the Controller after the end of the provision of services relating to processing, and shall delete existing copies unless Union or Member State law requires storage of the Personal Data. The Processor shall certify in writing that it has complied with this obligation within 30 days of termination.",
            "negotiation_notes": "Always require written certification of deletion. Specify the timeframe (30 days max). Ensure the obligation extends to sub-processors.",
            "risk_if_deviated": "Article 28(3)(g) GDPR. Without deletion obligations, Personal Data may be retained indefinitely by the Processor.",
            "importance_weight": 0.9,
            "order_index": 8,
        },
        {
            "clause_type": "audit_rights",
            "clause_name": "Audit and Inspection Rights",
            "position": "preferred",
            "standard_language": "The Processor shall make available to the Controller all information necessary to demonstrate compliance with the obligations laid down in Article 28 of the GDPR and allow for and contribute to audits, including inspections, conducted by the Controller or another auditor mandated by the Controller.",
            "fallback_language": "The Processor shall make available to the Controller all information necessary to demonstrate compliance with this Agreement, and shall allow for audits by the Controller or its appointed auditor, subject to reasonable notice of not less than 30 days and no more than one audit per year.",
            "negotiation_notes": "Accept reasonable limitations on frequency (1-2 per year) and notice period (30 days). Do not accept clauses that eliminate audit rights entirely or limit them to SOC 2 reports only.",
            "risk_if_deviated": "Article 28(3)(h) GDPR. Audit rights are mandatory and cannot be contracted away.",
            "importance_weight": 1.0,
            "order_index": 9,
        },
        {
            "clause_type": "international_transfer",
            "clause_name": "International Data Transfers",
            "position": "preferred",
            "standard_language": "The Processor shall not transfer Personal Data to a country outside the European Economic Area unless: (a) the European Commission has issued an adequacy decision for that country; (b) appropriate safeguards have been provided in accordance with Article 46 GDPR, including Standard Contractual Clauses approved by the European Commission; or (c) a derogation under Article 49 GDPR applies. The Processor shall inform the Controller of any transfers and the safeguards relied upon.",
            "unacceptable_patterns": ["transfers at Processor's discretion", "no safeguards required", "blanket consent to all jurisdictions"],
            "risk_if_deviated": "Articles 44-49 GDPR. Unlawful international transfers can result in fines and injunctions (cf. Schrems II).",
            "importance_weight": 1.0,
            "order_index": 10,
        },
        {
            "clause_type": "dpia_assistance",
            "clause_name": "Data Protection Impact Assessment Assistance",
            "position": "preferred",
            "standard_language": "The Processor shall provide reasonable assistance to the Controller in ensuring compliance with the obligations pursuant to Articles 32 to 36 of the GDPR, taking into account the nature of processing and the information available to the Processor.",
            "risk_if_deviated": "Article 28(3)(f) GDPR. Mandatory obligation that cannot be excluded.",
            "importance_weight": 0.7,
            "order_index": 11,
        },
        {
            "clause_type": "liability",
            "clause_name": "Liability and Indemnification",
            "position": "preferred",
            "standard_language": "The Processor shall indemnify the Controller against all claims, actions, third party claims, losses, damages and expenses incurred by the Controller which arise directly or indirectly from the Processor's breach of this Agreement or any of its obligations under the GDPR.",
            "fallback_language": "Each party shall be liable for its own breaches of this Agreement. The Processor's total aggregate liability under this Agreement shall not exceed the fees paid by the Controller in the 12 months preceding the event giving rise to the claim.",
            "negotiation_notes": "Push for uncapped liability for data protection breaches. At minimum, ensure the cap is separate from the main agreement's liability cap.",
            "risk_if_deviated": "Low liability caps may leave the Controller exposed to regulatory fines and data subject compensation claims under Articles 82-83 GDPR.",
            "importance_weight": 0.8,
            "order_index": 12,
        },
    ],
}
