"""Standard NDA playbook — mutual non-disclosure agreement positions."""

NDA_PLAYBOOK = {
    "name": "Standard NDA Playbook",
    "description": "Standard negotiation positions for mutual non-disclosure agreements. Covers definition of confidential information, exclusions, term, permitted use, return/destruction, and remedies.",
    "document_type": "nda",
    "jurisdiction": None,
    "clauses": [
        {
            "clause_type": "confidentiality",
            "clause_name": "Definition of Confidential Information",
            "position": "preferred",
            "standard_language": "\"Confidential Information\" means all non-public information disclosed by one party to the other, whether orally, in writing, or in any other form, that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure.",
            "fallback_language": "\"Confidential Information\" means all information disclosed by the Disclosing Party to the Receiving Party that is marked as \"Confidential\" at the time of disclosure, or if disclosed orally, is identified as confidential at the time of disclosure and confirmed in writing within 30 days.",
            "unacceptable_patterns": ["only written information", "only information marked confidential with no oral carve-out"],
            "negotiation_notes": "Prefer broad catch-all definition. Marking requirements are acceptable as fallback but ensure oral disclosures are covered with a reasonable confirmation period.",
            "risk_if_deviated": "Narrow definitions may leave commercially sensitive information unprotected.",
            "importance_weight": 1.0,
            "order_index": 1,
        },
        {
            "clause_type": "exclusions",
            "clause_name": "Standard Exclusions",
            "position": "preferred",
            "standard_language": "Confidential Information does not include information that: (a) is or becomes publicly available through no fault of the Receiving Party; (b) was known to the Receiving Party prior to disclosure without restriction; (c) is independently developed by the Receiving Party without reference to the Confidential Information; or (d) is rightfully received from a third party without restriction on disclosure.",
            "unacceptable_patterns": ["no exclusions", "residuals clause without limitation"],
            "negotiation_notes": "These four standard exclusions are market standard and should always be present. A residuals clause (permitting use of information retained in unaided memory) is acceptable if narrowly scoped.",
            "importance_weight": 0.9,
            "order_index": 2,
        },
        {
            "clause_type": "term",
            "clause_name": "Term and Duration of Obligations",
            "position": "preferred",
            "standard_language": "This Agreement shall remain in effect for a period of 2 years from the Effective Date. The obligations of confidentiality shall survive termination or expiration of this Agreement for a period of 3 years, except with respect to trade secrets which shall be protected for as long as they remain trade secrets under applicable law.",
            "fallback_language": "This Agreement shall remain in effect for 3 years. Confidentiality obligations survive for 5 years from disclosure.",
            "unacceptable_patterns": ["perpetual obligations on all information", "obligations expire on termination", "term less than 1 year"],
            "negotiation_notes": "2-3 year term is market standard. Survival of 3-5 years for confidentiality obligations is standard. Trade secrets should have perpetual protection.",
            "importance_weight": 0.8,
            "order_index": 3,
        },
        {
            "clause_type": "permitted_use",
            "clause_name": "Permitted Use and Purpose Limitation",
            "position": "preferred",
            "standard_language": "The Receiving Party shall use the Confidential Information solely for the Purpose (as defined herein) and shall not use the Confidential Information for any other purpose without the prior written consent of the Disclosing Party.",
            "negotiation_notes": "Ensure the Purpose is narrowly and specifically defined. Reject broad purposes like 'general business evaluation'.",
            "risk_if_deviated": "Broad permitted use effectively negates the NDA's protection.",
            "importance_weight": 1.0,
            "order_index": 4,
        },
        {
            "clause_type": "return_destruction",
            "clause_name": "Return or Destruction of Information",
            "position": "preferred",
            "standard_language": "Upon termination of this Agreement or upon the Disclosing Party's written request, the Receiving Party shall promptly return or destroy all Confidential Information and any copies thereof, and shall certify in writing that it has done so. The Receiving Party may retain one archival copy solely for legal compliance purposes, provided such copy remains subject to the confidentiality obligations herein.",
            "negotiation_notes": "The archival copy carve-out is market standard. Ensure it is limited to legal/compliance purposes only and remains subject to the NDA.",
            "importance_weight": 0.7,
            "order_index": 5,
        },
        {
            "clause_type": "remedies",
            "clause_name": "Remedies for Breach",
            "position": "preferred",
            "standard_language": "The parties acknowledge that a breach of this Agreement may cause irreparable harm for which monetary damages would be an inadequate remedy. Accordingly, the Disclosing Party shall be entitled to seek equitable relief, including injunction and specific performance, in addition to all other remedies available at law or in equity, without the necessity of proving actual damages or posting a bond.",
            "negotiation_notes": "Standard provision. Ensure it does not waive the right to monetary damages.",
            "importance_weight": 0.8,
            "order_index": 6,
        },
    ],
}
