"""Nigeria Data Protection Regulation (NDPR) compliance playbook.

Based on the NDPR 2019, NDPR Implementation Framework 2020, and the
Nigeria Data Protection Act 2023.
"""

NDPR_PLAYBOOK = {
    "name": "NDPR Data Protection Compliance",
    "description": "Standard positions for reviewing data processing agreements and privacy policies under the Nigeria Data Protection Regulation (NDPR) and Nigeria Data Protection Act 2023. Covers consent, data subject rights, cross-border transfers, breach notification, and DPO requirements.",
    "document_type": "dpa",
    "jurisdiction": "NG",
    "clauses": [
        {
            "clause_type": "lawful_basis",
            "clause_name": "Lawful Basis for Processing",
            "position": "preferred",
            "standard_language": "The Data Controller shall process Personal Data only where at least one of the following lawful bases applies: (a) the Data Subject has given consent to the processing; (b) the processing is necessary for the performance of a contract to which the Data Subject is party; (c) the processing is necessary for compliance with a legal obligation; (d) the processing is necessary to protect the vital interests of the Data Subject; (e) the processing is necessary for the performance of a task carried out in the public interest; or (f) the processing is necessary for the legitimate interests pursued by the Controller, except where such interests are overridden by the fundamental rights and freedoms of the Data Subject.",
            "negotiation_notes": "Consent under NDPR must be freely given, specific, informed, and unambiguous. Ensure consent mechanisms are granular and documented. Note: the Nigeria Data Protection Act 2023 aligns with GDPR principles.",
            "risk_if_deviated": "Processing without a lawful basis violates Section 25 of the Nigeria Data Protection Act 2023 and Regulation 2.2 of the NDPR.",
            "importance_weight": 1.0,
            "order_index": 1,
        },
        {
            "clause_type": "consent_mechanism",
            "clause_name": "Consent Requirements",
            "position": "preferred",
            "standard_language": "Where processing is based on consent, the Data Controller shall ensure that: (a) consent is obtained before processing commences; (b) the request for consent is presented clearly and in plain language; (c) consent is specific to each purpose of processing; (d) the Data Subject is informed of the right to withdraw consent at any time; and (e) withdrawal of consent is as easy as giving consent.",
            "unacceptable_patterns": ["implied consent", "pre-ticked boxes", "bundled consent with terms of service", "consent cannot be withdrawn"],
            "risk_if_deviated": "Invalid consent renders all processing unlawful. NITDA can impose fines of up to 2% of annual gross revenue or NGN 10 million, whichever is greater.",
            "importance_weight": 1.0,
            "order_index": 2,
        },
        {
            "clause_type": "privacy_notice",
            "clause_name": "Privacy Notice and Transparency",
            "position": "preferred",
            "standard_language": "The Data Controller shall provide the Data Subject with the following information at or before the time of collection: (a) the identity and contact details of the Controller; (b) the purpose of the processing; (c) the categories of Personal Data concerned; (d) the recipients or categories of recipients; (e) any intention to transfer data to a foreign country; (f) the period of storage or criteria for determining it; (g) the Data Subject's rights; and (h) the right to lodge a complaint with NITDA.",
            "risk_if_deviated": "Failure to provide adequate notice violates the NDPR transparency requirements and may attract enforcement action by NITDA.",
            "importance_weight": 0.9,
            "order_index": 3,
        },
        {
            "clause_type": "data_subject_rights",
            "clause_name": "Data Subject Rights",
            "position": "preferred",
            "standard_language": "The Data Controller shall facilitate the exercise of the following Data Subject rights: (a) right of access; (b) right to rectification; (c) right to erasure; (d) right to restrict processing; (e) right to data portability; (f) right to object to processing; and (g) right not to be subject to automated decision-making. Requests shall be responded to within 30 days.",
            "negotiation_notes": "The NDPR Implementation Framework specifies a 30-day response period. Ensure internal processes can meet this deadline.",
            "risk_if_deviated": "Failure to honour data subject rights attracts regulatory action under the NDPR and Nigeria Data Protection Act 2023.",
            "importance_weight": 1.0,
            "order_index": 4,
        },
        {
            "clause_type": "international_transfer",
            "clause_name": "Cross-Border Data Transfer",
            "position": "preferred",
            "standard_language": "Personal Data shall not be transferred to a foreign country unless: (a) the recipient country has adequate data protection laws as determined by NITDA; (b) the Data Controller has provided appropriate safeguards including binding corporate rules, standard contractual clauses, or codes of conduct; or (c) the Data Subject has given explicit consent to the transfer after being informed of the risks.",
            "unacceptable_patterns": ["unrestricted transfers", "no safeguards required", "transfers at processor's sole discretion"],
            "negotiation_notes": "NITDA has not published a formal adequacy list. In practice, transfers should be protected by contractual safeguards modelled on EU Standard Contractual Clauses.",
            "risk_if_deviated": "Section 42 of the Nigeria Data Protection Act 2023 restricts cross-border transfers. Violations attract penalties.",
            "importance_weight": 1.0,
            "order_index": 5,
        },
        {
            "clause_type": "breach_notification",
            "clause_name": "Data Breach Notification",
            "position": "preferred",
            "standard_language": "In the event of a Personal Data breach, the Data Controller shall: (a) notify NITDA within 72 hours of becoming aware of the breach; (b) notify the affected Data Subjects without undue delay where the breach is likely to result in a high risk to their rights and freedoms; and (c) document all breaches including the facts, effects, and remedial action taken. The Data Processor shall notify the Controller within 24 hours of discovering a breach.",
            "negotiation_notes": "The 72-hour notification to NITDA aligns with GDPR standards. Ensure the Processor's notification to the Controller is faster (24 hours) to allow time for assessment.",
            "risk_if_deviated": "Failure to report breaches within the prescribed timeframe may result in additional penalties and reputational damage.",
            "importance_weight": 1.0,
            "order_index": 6,
        },
        {
            "clause_type": "dpo_appointment",
            "clause_name": "Data Protection Officer Appointment",
            "position": "preferred",
            "standard_language": "Where required under the NDPR or Nigeria Data Protection Act 2023, the Data Controller shall appoint a Data Protection Officer (DPO) who shall: (a) be independent in the performance of their duties; (b) have expert knowledge of data protection law and practices; (c) report directly to senior management; and (d) be the point of contact for NITDA and Data Subjects.",
            "negotiation_notes": "DPO appointment is mandatory for organisations processing personal data of more than 2,000 data subjects in a 6-month period. Consider outsourced DPO services for smaller organisations.",
            "risk_if_deviated": "Failure to appoint a DPO when required violates Article 32 of the NDPR Implementation Framework.",
            "importance_weight": 0.8,
            "order_index": 7,
        },
        {
            "clause_type": "data_retention",
            "clause_name": "Data Retention and Deletion",
            "position": "preferred",
            "standard_language": "Personal Data shall be retained only for as long as necessary to fulfil the purpose for which it was collected. The Data Controller shall establish a data retention schedule and shall securely delete or anonymise Personal Data when the retention period expires or the processing purpose has been fulfilled. The Data Controller shall certify deletion upon request.",
            "negotiation_notes": "Require specific retention periods in the contract rather than open-ended retention. Ensure deletion extends to backups within a reasonable timeframe.",
            "risk_if_deviated": "Indefinite retention violates the storage limitation principle under both NDPR and the Nigeria Data Protection Act 2023.",
            "importance_weight": 0.8,
            "order_index": 8,
        },
        {
            "clause_type": "security_measures",
            "clause_name": "Security of Personal Data",
            "position": "preferred",
            "standard_language": "The Data Controller and Data Processor shall implement appropriate technical and organisational measures to protect Personal Data against unauthorised or unlawful processing and against accidental loss, destruction, or damage, including: (a) encryption of Personal Data in transit and at rest; (b) access controls and authentication; (c) regular security testing and vulnerability assessments; (d) staff training on data protection; and (e) incident response procedures.",
            "risk_if_deviated": "Inadequate security measures violate Regulation 2.6 of the NDPR and expose the organisation to breach liability.",
            "importance_weight": 1.0,
            "order_index": 9,
        },
        {
            "clause_type": "audit_filing",
            "clause_name": "NDPR Audit and Filing Requirements",
            "position": "preferred",
            "standard_language": "The Data Controller shall: (a) conduct a Data Protection Audit within 6 months of this Agreement and annually thereafter; (b) file the audit report with NITDA through a licensed Data Protection Compliance Organisation (DPCO); and (c) maintain records of all processing activities as required under the NDPR Implementation Framework.",
            "negotiation_notes": "Annual NDPR audit filing is mandatory for all data controllers processing personal data of Nigerian data subjects. Failure to file attracts penalties.",
            "risk_if_deviated": "Non-filing of the annual NDPR audit is a regulatory offence that can result in fines and enforcement action by NITDA.",
            "importance_weight": 0.9,
            "order_index": 10,
        },
    ],
}
