"""SaaS Agreement playbook — standard positions for software subscription contracts."""

SAAS_AGREEMENT_PLAYBOOK = {
    "name": "SaaS Agreement Playbook",
    "description": "Standard negotiation positions for SaaS subscription agreements covering liability, IP, data, SLA, and termination.",
    "document_type": "service_agreement",
    "jurisdiction": None,
    "clauses": [
        {
            "clause_type": "liability",
            "clause_name": "Limitation of Liability",
            "position": "preferred",
            "standard_language": "Each party's total aggregate liability under this Agreement shall not exceed the total fees paid or payable by the Customer in the 12-month period immediately preceding the event giving rise to the claim. Neither party shall be liable for any indirect, incidental, special, consequential, or punitive damages.",
            "fallback_language": "Liability capped at 24 months of fees. Consequential damages excluded except for breaches of confidentiality, IP infringement, and data protection obligations.",
            "unacceptable_patterns": ["uncapped liability", "cap less than 6 months fees", "waiver of all consequential damages without carve-outs"],
            "negotiation_notes": "12-month cap is standard. Push for super-cap (2-3x fees) for IP indemnification and data breaches. Never accept uncapped liability.",
            "risk_if_deviated": "Uncapped liability or very low caps expose the organisation to disproportionate risk.",
            "approval_required_if": "Cap below 6 months or above 36 months of fees",
            "importance_weight": 1.0,
            "order_index": 1,
        },
        {
            "clause_type": "indemnity",
            "clause_name": "IP Indemnification",
            "position": "preferred",
            "standard_language": "The Provider shall indemnify, defend, and hold harmless the Customer from and against any third-party claims alleging that the Customer's use of the Service in accordance with this Agreement infringes any intellectual property right of a third party. The Provider shall, at its option: (a) procure the right for the Customer to continue using the Service; (b) modify the Service to be non-infringing; or (c) terminate the affected Service and refund prepaid fees on a pro-rata basis.",
            "unacceptable_patterns": ["no IP indemnification", "customer indemnifies provider for IP claims", "indemnification limited to patents only"],
            "negotiation_notes": "IP indemnification from the provider is market standard for SaaS. Ensure it covers all IP rights, not just patents. The mitigation options (modify/replace/refund) are standard.",
            "importance_weight": 1.0,
            "order_index": 2,
        },
        {
            "clause_type": "data_ownership",
            "clause_name": "Customer Data Ownership",
            "position": "preferred",
            "standard_language": "As between the parties, the Customer retains all right, title, and interest in and to the Customer Data. The Provider acquires no rights in the Customer Data except the limited licence to process it as necessary to provide the Service. The Provider shall not access, use, or disclose Customer Data except as necessary to provide the Service or as directed by the Customer.",
            "unacceptable_patterns": ["provider owns aggregated data", "provider may use customer data for product improvement", "broad licence to customer data"],
            "risk_if_deviated": "Broad data usage rights may expose confidential business data and create regulatory risk under data protection laws.",
            "importance_weight": 1.0,
            "order_index": 3,
        },
        {
            "clause_type": "termination",
            "clause_name": "Termination for Convenience",
            "position": "preferred",
            "standard_language": "Either party may terminate this Agreement for convenience upon 30 days' prior written notice. Upon termination, the Customer shall be entitled to a pro-rata refund of any prepaid fees for the unused portion of the subscription term. The Provider shall make Customer Data available for export for a period of 30 days following termination.",
            "fallback_language": "The Customer may terminate for convenience at the end of any subscription term by providing 60 days' prior written notice. No refund for the current term, but no auto-renewal without affirmative consent.",
            "unacceptable_patterns": ["no termination for convenience", "auto-renewal without notice", "data deleted immediately on termination"],
            "negotiation_notes": "Always ensure there is a data export period post-termination (minimum 30 days). Avoid lock-in clauses with no exit.",
            "importance_weight": 0.9,
            "order_index": 4,
        },
        {
            "clause_type": "sla",
            "clause_name": "Service Level Agreement",
            "position": "preferred",
            "standard_language": "The Provider shall maintain Service availability of at least 99.9% measured monthly, excluding scheduled maintenance. If the Provider fails to meet this commitment, the Customer shall be entitled to service credits equal to 10% of the monthly fee for each 0.1% below the target, up to a maximum of 30% of the monthly fee. Service credits are the Customer's sole and exclusive remedy for failure to meet the SLA.",
            "fallback_language": "99.5% uptime with 5% service credits per 0.5% below target.",
            "negotiation_notes": "99.9% is the market standard for enterprise SaaS. Always require measurable SLAs with financial remedies, not just 'commercially reasonable efforts'.",
            "risk_if_deviated": "Without measurable SLAs, the Customer has no recourse for service outages.",
            "importance_weight": 0.8,
            "order_index": 5,
        },
    ],
}
